development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:dec0eb17fa307e42edff32abb8840902@pearlfish.redistogo.com:10065/
  channel_prefix: devcamp_portfolio_production
